### ISSUE TITLE
Error when running npm start

### ISSUE THREAD

**Issue by progravi** [formio/react-app-starterkit#10]
Getting below error after i cloned the project and trying to run(npm start). i installed the required packages using npm install.

Failed to compile.
./node_modules/react-formio/lib/index.js
Module not found: Can't resolve 'formiojs/components/base/editForm/utils' in 'C:\Git\formio\react-app-starterkit\node_modules\react-formio\lib'

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
