### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rahulseth625** [formio/react-app-starterkit#17]
- Formio.js version: "^4.0.0-rc.21",
- Frontend framework: "react": "16.8.2",
- Browser: chrome
- Browser version: Version 88.0.4324.104 (Official Build) (64-bit)

## Steps to Reproduce
1.  click on create form link
2.   A create form will open and after filling the form titile , name , display as , type and path , click on create form
3.    After click on create form gives the error as - Cast to ObjectId failed for value "form" at path "_id" for model "form"

## Expected behavior
should be create a new form
## Observed behavior
got an error - Cast to ObjectId failed for value "form" at path "_id" for model "form"

## Example
![bug](https://user-images.githubusercontent.com/33866915/105833810-ba28f180-5fef-11eb-8d6a-83c7b5dfbe8d.png)

![bug2](https://user-images.githubusercontent.com/33866915/105835385-bf873b80-5ff1-11eb-94ea-a24be85dea26.png)

I am getting an empty string in form id .
kindly pls help....!!
```

**Comment by AlexeyDavyd** [comment]
Was not able to replicate issue.

Could you please try to create separate Form.io project and use it instead of default.
To do that you should replace PROJECT_URL variable in config.js with your own project Live Endpoint that you can take on portal:
![image](https://user-images.githubusercontent.com/47381348/106010772-df3e6280-60ca-11eb-8c43-2e146a41b9d5.png)

And try the same steps.

**Comment by rahulseth625** [comment]
@AlexeyDavyd  Can I save all those data to my own database?

**Comment by AlexeyDavyd** [comment]
You either can deploy our server to your own environment.
Or you can sue hooks and events to save data to your own database along with our regular workflow.

**Comment by AlexeyDavyd** [comment]
@rahulseth625 The reason of that error is you sending string "form" as form id. And our server failed trying to cast that to ObjectId

**Comment by rahulseth625** [comment]
@AlexeyDavyd  I am getting unauthorized error while submitting the form.
![unauthorized](https://user-images.githubusercontent.com/33866915/106456314-5866fc80-64b3-11eb-8e9a-0e132c6a0fe3.png)

**Comment by AlexeyDavyd** [comment]
Make sure to set proper authentication settings for your form:
![image](https://user-images.githubusercontent.com/47381348/106456877-2d72ad80-649f-11eb-89b3-619a691df347.png)

**Comment by rahulseth625** [comment]
@AlexeyDavyd this form is from the react formio startup kit. So can I use this form in my  own PROJECT_URL which is live end point. Is that the reason i am getting unauthorized error?

**Comment by AlexeyDavyd** [comment]
You can import that form into your project using Form Import.
![image](https://user-images.githubusercontent.com/47381348/106458111-f56c6a00-64a0-11eb-8661-3b154e319a5e.png)

And replace default starterkit project with your own in config.js file.
Also you should tag your form as 'common' on form settings page in order to see that form in form list of starterkit.

**Comment by rahulseth625** [comment]
@AlexeyDavyd ...As you said I can use that form which I make inside my live end point (project url) under from section by making a new form and providing the embedded url in my project  but I don't use that one I want to use this form.io startup kit source code form and I am getting two errors as before said Cast to ObjectId failed for value "form" at path "_id" for model "form" and unauthorized. Can you please let me know how to handle these errors.
Thank you ...!!

**Comment by wag110894** [comment]
Hello @rahulseth625,

Thanks for reaching out! We have reviewed this item and believe that this is an issue on your side.  We do offer Support Packages that are for training, support or development services. The hours can be used in one-hour increments at your convenience over a 90 day period.  We will assign one of our senior developers to work directly with you in online sessions.  Please let me know if you are interested and I can provide you with the documentation.

Thank you.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
