### ISSUE TITLE
getting page is undefined in Submission Grid 

### ISSUE THREAD

**Issue by rahulseth625** [formio/react-app-starterkit#20]
## Environment
Formio.js version: "^4.0.0-rc.21",
Frontend framework: "react": "16.8.2",
Browser: chrome
Browser version: Version 88.0.4324.104 (Official Build) (64-bit)

I am getting page is undefined and did not get the columns value using the SubmissionGrid to view the submission data in the 
form with columns and its values.

## Observed behavior - get the form with columns but the columns shows nothing after click on View Data
![sub](https://user-images.githubusercontent.com/33866915/116234569-66f34600-a77a-11eb-9e93-196a1aefd974.png)

                     <SubmissionGrid
                        form = {form}
                        submissions={submissions}
                        getSubmissions={getSubmissions}
                        onAction={onAction}
                      />
Under SubmissionGrid -
submissions = { submissions} where {submissions} contains as below
![sub](https://user-images.githubusercontent.com/33866915/116236367-9c009800-a77c-11eb-8671-bac1edf0cb40.png)

Here am getting pagination: {numPages: 0, page: 1, total: 0}. 
So how to fix it.
Kindly pls help.

Also submissions.submissions is below -
![sub](https://user-images.githubusercontent.com/33866915/116238329-d834f800-a77e-11eb-8d74-449e14658a6e.png)

Also form = {form} where {form} contain as below.
{id: "2", isActive: false, lastUpdated: 0, form: {…}, url: "https://reactstarter.form.io/form/2", …}
![ff](https://user-images.githubusercontent.com/33866915/116236106-462bf000-a77c-11eb-8b52-1e2fcfb5f16b.png)

Also getSubmissions={getSubmissions} where {getSubmissions} contain as below.
(page, query) => dispatch(Object(react_formio__WEBPACK_IMPORTED_MODULE_4__["getSubmissions"])('submissions', page, query, ownProps.match.params.formId))

The Whole Code is -

                render() {
                    const { match: { params: { formId } } } = this.props
                    const { form, submissions, isLoading, onAction, getSubmissions, errors } = this.props
                
                    if (isLoading) {
                      return (
                        <Loading />
                      );
                    }
                
                
                    return (
                      <div className='form-index' >
                       <Errors errors={errors} /> 
                
                          <SubmissionGrid
                            form = {form}
                            submissions={submissions}
                            getSubmissions={getSubmissions}
                            onAction={onAction}
                          />
                
                        <Link className='btn btn-primary' to={`/form/${formId}`}>
                          <i className='glyphicon glyphicon-plus fa fa-plus' aria-hidden='true'></i>
                          New
                         {form.title} 
                        </Link>
                      </div >
                    );
                  }
                }
                
                
                const mapStateToProps = (state, ownProps) => {
                
                  const form = selectRoot('form', state);
                  const submissions = selectRoot('submissions', state);
                
                  return {
                    form: form,
                    submissions: submissions,
                    getSubmissions: getSubmissions,
                    isLoading: form.isActive || submissions.isActive,
                    errors: [
                      selectError('submissions', state),
                      selectError('form', state)
                    ]
                  };
                };
                
                const mapDispatchToProps = (dispatch, ownProps) => {
                  return {
                    getSubmissions: (page, query) => 
                    dispatch(getSubmissions('submissions', page, query, ownProps.match.params.formId    
                    )),
                    onAction: (submission, action) => {
                      switch (action) {
                        case 'view':
                        case 'row':
                          dispatch(push(`/form/${ownProps.match.params.formId}/submission/${submission.id}`));
                          break;
                        case 'edit':
                          dispatch(push(`/form/${ownProps.match.params.formId}/submission/${submission.id}/edit`));
                          break;
                        case 'delete':
                          dispatch(push(`/form/${ownProps.match.params.formId}/submission/${submission.id}/delete`));
                          break;
                        default:
                      }
                    },
                  };
                };
                
                export default connect(
                  mapStateToProps,
                  mapDispatchToProps
                )(List)
                
Kindly please help me.
Thanks in advance !

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
