### ISSUE TITLE
Can't build react-app-starterkit in either development or production mode

### ISSUE THREAD

**Issue by mfreeman-xtivia** [formio/react-app-starterkit#3]
Attempting to run both "npm run serve" and "npm run build" throw the following exception...any quick ideas on what might be wrong here? (node=8.9.4, npm=5.6.0)

```
ERROR in ./~/react-formio/lib/modules/submission/containers/SubmissionGrid.js
Module not found: Error: Can't resolve 'formiojs/build/components' in '/home/mfreeman/Projects/temp/react-app-starterkit/node_modules/react-formio/lib/modules/submission/containers'
 @ ./~/react-formio/lib/modules/submission/containers/SubmissionGrid.js 19:18-54
 @ ./~/react-formio/lib/modules/resource/containers/Index.js
 @ ./~/react-formio/lib/modules/resource/routes.js
 @ ./~/react-formio/lib/modules/resource/index.js
 @ ./src/app/resources/event/index.js
 @ ./src/app/resources/index.js
 @ ./src/index.js
```

**Comment by travist** [comment]
This happened with the latest ```formiojs``` release, where these components were added to the ```lib``` folder instead of ```build```

**Comment by randallknutson** [comment]
Pull the latest and see if it is fixed for you now.

**Comment by mfreeman-xtivia** [comment]
Sorry--not sure of the precise instructions you want me to try? update the package dependency here in package.json to react-formio 2.0.5?
