### ISSUE TITLE
Custom Component works from Edit Form Enter Data, not from Form List Enter Data

### ISSUE THREAD

**Issue by Beatusvir** [formio/react-app-starterkit#38]
Greetings!

As the title says, I created a couple of custom components, I thought everything was working fine until I realized the behavior described. When I'm on the FormGrid Component, there are 3 buttons: Enter Data, View Data, Edit Form.
![image](https://user-images.githubusercontent.com/10576465/156443777-33c0b142-7720-463e-a952-e24e2ffb4e6e.png)

If I click enter data, the form shows but only the label of the custom component shows, and I can see the input blinking out of the page.
![image](https://user-images.githubusercontent.com/10576465/156444015-51c40931-7223-4117-a2eb-9574b20a1b8a.png)

This is easy to check when using the profiler, this is a picture of it (not sure how to get a better image out of the profiler)
![image](https://user-images.githubusercontent.com/10576465/156444368-a3143f17-e073-41a4-a691-0bd20fa72ce3.png)

And just a few moments later its gone
![image](https://user-images.githubusercontent.com/10576465/156444439-7a8070fa-491a-4537-b327-935b9586f600.png)

However, if I'm inside the Edit Form Page and click Enter Data, the component shows correctly.
![image](https://user-images.githubusercontent.com/10576465/156444218-4566752e-4d44-4742-a031-7100fcc1be93.png)

Any ideas of what could be causing this?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
