### ISSUE TITLE
DataGrid Example Requested

### ISSUE THREAD

**Issue by mfreeman-xtivia** [formio/react-app-starterkit#4]
Does the React form.io implementation support/provide a DataGrid component to view submisions the way that the AngularJS/Angular implementations do?

If so is there an example of how to specify/use this Grid component? I can see a Grid component in the source, and some usage of it inside another component, but I got a little lost trying to understand how I might use it in my own code?

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
