### ISSUE TITLE
[BUG] Please clarify where the PROJECT_URL can be found on the form.io dashboard

### ISSUE THREAD

**Issue by zachsa** [formio/react-app-starterkit#45]
Please can you clarify what the project URL is referring to:

>Modify the src/config.js file to point the PROJECT_URL variable to the project you created in form.io

I see:

- The URL of the page in the Chrome address bar
- A 'live' endpoint that that seems to be the API_URL value

After starting the app I don't see any forms, I'm not sure that the project has been picked up as I can't see forms

**Comment by zachsa** [comment]
The walkthrough in the project was very helpful - I'm still not clear what the configuration in the app is for (since really I was just testing how to render a React form).

Now that I know the formio/react library is for rendering form from JSON created via the form builder the whole library ecosystem makes a lot more sense.

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
