### ISSUE TITLE
Module not found: Error: Can't resolve, Please help me with this

### ISSUE THREAD

**Issue by misterharshith** [formio/react-app-starterkit#6]
### formiojs v2.32.3, react-formio v2.1.1, node v8.11.4 and npm 5.6.0 
Im getting following error when I execute npm run serve

ERROR in ./~/react-formio/lib/modules/auth/containers/Login.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/auth/containers'
 @ ./~/react-formio/lib/modules/auth/containers/Login.js 11:14-51
 @ ./~/react-formio/lib/modules/auth/routes.js
 @ ./~/react-formio/lib/modules/auth/index.js
 @ ./src/app/auth/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

ERROR in ./~/react-formio/lib/modules/auth/containers/Register.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/auth/containers'
 @ ./~/react-formio/lib/modules/auth/containers/Register.js 11:14-51
 @ ./~/react-formio/lib/modules/auth/routes.js
 @ ./~/react-formio/lib/modules/auth/index.js
 @ ./src/app/auth/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

ERROR in ./~/react-formio/lib/modules/resource/containers/Edit.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/resource/containers'
 @ ./~/react-formio/lib/modules/resource/containers/Edit.js 11:14-51
 @ ./~/react-formio/lib/modules/resource/routes.js
 @ ./~/react-formio/lib/modules/resource/index.js
 @ ./src/app/resources/activity/index.js
 @ ./src/app/resources/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

ERROR in ./~/react-formio/lib/modules/resource/containers/View.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/resource/containers'
 @ ./~/react-formio/lib/modules/resource/containers/View.js 11:14-51
 @ ./~/react-formio/lib/modules/resource/routes.js
 @ ./~/react-formio/lib/modules/resource/index.js
 @ ./src/app/resources/activity/index.js
 @ ./src/app/resources/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

ERROR in ./~/react-formio/lib/modules/resource/containers/Create.js
Module not found: Error: Can't resolve '../../../components/Formio' in '/Users/activemac05/Desktop/main-project/react-app-starterkit/node_modules/react-formio/lib/modules/resource/containers'
 @ ./~/react-formio/lib/modules/resource/containers/Create.js 11:14-51
 @ ./~/react-formio/lib/modules/resource/routes.js
 @ ./~/react-formio/lib/modules/resource/index.js
 @ ./src/app/resources/activity/index.js
 @ ./src/app/resources/index.js
 @ ./src/index.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client ./src/index

**Comment by daneformio** [comment]
Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
